# Generated by Django 4.2.16 on 2024-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience_level',
            field=models.CharField(choices=[('LEARNER', 'Learner'), ('INTERMEDIATE', 'Intermediate'), ('PROFESSIONAL', 'Professional')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('FRONTEND', 'Frontend Developer'), ('BACKEND', 'Backend Developer'), ('DEVOPS', 'Devops Engineer')], max_length=50),
        ),
    ]
